"""Create and verify PostgreSQL backups for the local Compose environment."""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import BinaryIO
from uuid import uuid4

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
BACKUP_DIRECTORY = REPOSITORY_ROOT / "backups"
SAFE_DATABASE_NAME = re.compile(r"^tap_restore_smoke_[0-9a-f]{32}$")


class BackupCommandError(RuntimeError):
    """Raised when a Docker Compose PostgreSQL operation fails."""


def _compose(*arguments: str) -> list[str]:
    return ["docker", "compose", "exec", "-T", "postgres", *arguments]


def _run(
    arguments: list[str],
    *,
    stdin: BinaryIO | int = subprocess.DEVNULL,
    stdout: BinaryIO | int = subprocess.PIPE,
) -> subprocess.CompletedProcess[bytes]:
    result = subprocess.run(
        arguments,
        cwd=REPOSITORY_ROOT,
        stdin=stdin,
        stdout=stdout,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        message = (result.stderr or b"").decode(errors="replace").strip()
        raise BackupCommandError(
            f"Command failed ({result.returncode}): {' '.join(arguments[:5])}\n{message}"
        )
    return result


def _ensure_local_environment() -> None:
    """Refuse to run destructive smoke-test operations outside local/test."""
    environment = os.environ.get("APP_ENV", "local").strip().lower()
    env_file = REPOSITORY_ROOT / ".env"
    if env_file.is_file():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            key, separator, value = line.partition("=")
            if separator and key.strip().lower() == "app_env":
                value = value.strip().strip("'\"")
                if "APP_ENV" not in os.environ:
                    environment = value.lower()
                break
    if environment not in {"local", "test"}:
        raise BackupCommandError(
            "This local Compose backup tool only runs when APP_ENV is 'local' or 'test'."
        )


def _backup_command() -> list[str]:
    return _compose(
        "sh",
        "-lc",
        'exec pg_dump --format=custom --no-owner --no-acl '
        '--username="$POSTGRES_USER" --dbname="$POSTGRES_DB"',
    )


def create_backup(destination: Path) -> None:
    """Write a custom-format dump without text-decoding binary output."""
    _ensure_local_environment()
    destination = destination.resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)

    created = False
    try:
        with destination.open("xb") as dump_file:
            created = True
            _run(_backup_command(), stdout=dump_file)
    except Exception:
        if created:
            destination.unlink(missing_ok=True)
        raise

    if destination.stat().st_size == 0:
        destination.unlink(missing_ok=True)
        raise BackupCommandError("PostgreSQL produced an empty backup file.")


def _scalar_query(database: str, query: str) -> str:
    safe_database = validate_smoke_database_name(database) if database.startswith(
        "tap_restore_smoke_"
    ) else database
    shell_command = (
        'exec psql --no-psqlrc --tuples-only --no-align --set=ON_ERROR_STOP=1 '
        '--username="$POSTGRES_USER" '
        f'--dbname="{safe_database}" --command="{query}"'
    )
    result = _run(_compose("sh", "-lc", shell_command))
    output = result.stdout
    if isinstance(output, bytes):
        output = output.decode(errors="strict")
    return output.strip()


def validate_smoke_database_name(database: str) -> str:
    """Allow cleanup only for names generated by this script."""
    if not SAFE_DATABASE_NAME.fullmatch(database):
        raise BackupCommandError("Refusing to operate on a non-generated smoke database name.")
    return database


def restore_smoke() -> None:
    """Restore a temporary dump into a disposable database and verify its schema revision."""
    _ensure_local_environment()
    smoke_database = validate_smoke_database_name(f"tap_restore_smoke_{uuid4().hex}")
    BACKUP_DIRECTORY.mkdir(parents=True, exist_ok=True)
    dump_path = BACKUP_DIRECTORY / f".restore-smoke-{uuid4().hex}.dump"

    created = False
    try:
        create_backup(dump_path)
        source_revision = _scalar_query(
            "$POSTGRES_DB",
            "SELECT version_num FROM alembic_version LIMIT 1",
        )
        _run(
            _compose(
                "sh",
                "-lc",
                'exec createdb --username="$POSTGRES_USER" "$1"',
                "restore-smoke",
                smoke_database,
            )
        )
        created = True

        with dump_path.open("rb") as dump_file:
            _run(
                _compose(
                    "pg_restore",
                    "--exit-on-error",
                    "--no-owner",
                    "--no-acl",
                    f"--dbname={smoke_database}",
                ),
                stdin=dump_file,
            )

        restored_revision = _scalar_query(
            smoke_database,
            "SELECT version_num FROM alembic_version LIMIT 1",
        )
        if not source_revision or restored_revision != source_revision:
            raise BackupCommandError(
                "Restore verification failed: the Alembic revision does not match the source."
            )

        print(
            "Restore smoke test passed "
            f"(Alembic revision {restored_revision}; temporary database will be removed)."
        )
    finally:
        if created:
            _run(
                _compose(
                    "sh",
                    "-lc",
                    'exec dropdb --if-exists --username="$POSTGRES_USER" "$1"',
                    "restore-smoke",
                    validate_smoke_database_name(smoke_database),
                )
            )
        dump_path.unlink(missing_ok=True)


def _default_backup_path() -> Path:
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    return BACKUP_DIRECTORY / f"tap-{timestamp}.dump"


def main() -> int:
    """Run the local PostgreSQL backup or restore smoke-test command."""
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    backup_parser = commands.add_parser("backup", help="Create a local custom-format backup.")
    backup_parser.add_argument("--output", type=Path, default=_default_backup_path())
    commands.add_parser(
        "restore-smoke",
        help="Back up, restore into a unique temporary database, verify, and clean up.",
    )
    arguments = parser.parse_args()

    try:
        if arguments.command == "backup":
            create_backup(arguments.output)
            print(f"Backup created: {arguments.output.resolve()}")
        else:
            restore_smoke()
        return 0
    except (BackupCommandError, OSError) as error:
        print(f"PostgreSQL backup error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
