"""Provider-neutral object-storage contract and server-owned object keys."""

from collections.abc import AsyncIterator, Mapping
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Protocol
from uuid import UUID


class ObjectStorageError(RuntimeError):
    """Raised when the object-storage provider cannot complete an operation."""


class ObjectNotFoundError(ObjectStorageError):
    """Raised when an object does not exist in object storage."""


@dataclass(frozen=True, slots=True)
class PresignedUpload:
    """A short-lived, provider-issued upload authorization."""

    url: str
    required_headers: Mapping[str, str]
    expires_at: datetime


@dataclass(frozen=True, slots=True)
class PresignedDownload:
    """A short-lived, attachment-only download authorization."""

    url: str
    expires_at: datetime


@dataclass(frozen=True, slots=True)
class StoredObjectMetadata:
    """Verified metadata returned by the object-storage provider."""

    content_type: str
    byte_size: int
    checksum_sha256: str | None


class ObjectStorage(Protocol):
    """Port implemented by MinIO/S3 adapters, never by API routes."""

    async def create_presigned_upload(
        self,
        *,
        object_key: str,
        content_type: str,
        checksum_sha256: str,
        expires_in: timedelta,
    ) -> PresignedUpload:
        """Authorize one short-lived upload for a server-generated object key."""

    async def create_presigned_download(
        self,
        *,
        object_key: str,
        filename: str,
        content_type: str,
        expires_in: timedelta,
    ) -> PresignedDownload:
        """Authorize a short-lived private attachment download."""

    async def create_presigned_preview(
        self,
        *,
        object_key: str,
        filename: str,
        content_type: str,
        expires_in: timedelta,
    ) -> PresignedDownload:
        """Authorize a short-lived private inline preview."""

    async def get_object_metadata(
        self,
        *,
        object_key: str,
    ) -> StoredObjectMetadata:
        """Return provider-verified metadata after an upload completes."""

    async def put_object(
        self,
        *,
        object_key: str,
        content_type: str,
        checksum_sha256: str,
        content: bytes,
    ) -> None:
        """Store bounded server-received content under a server-owned key."""

    async def delete_object(self, *, object_key: str) -> None:
        """Delete an object as part of retention or privacy workflows."""


class ObjectStorageReader(Protocol):
    """Trusted internal read access for background security services."""

    def iter_object_chunks(
        self,
        *,
        object_key: str,
        chunk_size: int = 64 * 1024,
    ) -> AsyncIterator[bytes]:
        """Yield server-owned object bytes without exposing a download URL."""


def candidate_document_object_key(
    *,
    tenant_id: UUID,
    candidate_id: UUID,
    document_id: UUID,
) -> str:
    """
    Return a deterministic, server-owned object key.

    The key deliberately excludes filename, email, and any other candidate PII.
    Its UUID-based IDs are generated by the application, never supplied by a client.
    """

    return f"v1/tenants/{tenant_id}/candidates/{candidate_id}/documents/{document_id}/content"


def public_application_resume_scan_object_key(
    *,
    tenant_id: UUID,
    scan_id: UUID,
) -> str:
    """Return a non-PII key reserved for one public résumé scan proof."""
    return f"v1/tenants/{tenant_id}/public-resume-scans/{scan_id}/content"
