"""Provider-neutral object-storage contract and server-owned object keys."""

from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Protocol
from uuid import UUID


class ObjectStorageError(RuntimeError):
    """Raised when the object-storage provider cannot complete an operation."""


class ObjectNotFoundError(ObjectStorageError):
    """Raised when an object does not exist in object storage."""


@dataclass(frozen=True, slots=True)
class PresignedUpload:
    """A short-lived, provider-issued upload authorization."""

    url: str
    required_headers: Mapping[str, str]
    expires_at: datetime


@dataclass(frozen=True, slots=True)
class StoredObjectMetadata:
    """Verified metadata returned by the object-storage provider."""

    content_type: str
    byte_size: int
    checksum_sha256: str | None


class ObjectStorage(Protocol):
    """Port implemented by MinIO/S3 adapters, never by API routes."""

    async def create_presigned_upload(
        self,
        *,
        object_key: str,
        content_type: str,
        checksum_sha256: str,
        expires_in: timedelta,
    ) -> PresignedUpload:
        """Authorize one short-lived upload for a server-generated object key."""

    async def get_object_metadata(
        self,
        *,
        object_key: str,
    ) -> StoredObjectMetadata:
        """Return provider-verified metadata after an upload completes."""

    async def delete_object(self, *, object_key: str) -> None:
        """Delete an object as part of retention or privacy workflows."""


def candidate_document_object_key(
    *,
    tenant_id: UUID,
    candidate_id: UUID,
    document_id: UUID,
) -> str:
    """
    Return a deterministic, server-owned object key.

    The key deliberately excludes filename, email, and any other candidate PII.
    Its UUID-based IDs are generated by the application, never supplied by a client.
    """

    return (
        f"v1/tenants/{tenant_id}/candidates/{candidate_id}/"
        f"documents/{document_id}/content"
    )
