"""add job postings

Revision ID: 1486de3f8469
Revises: 1f53479e2960
Create Date: 2026-09-10 13:03:55.870615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1486de3f8469'
down_revision: Union[str, Sequence[str], None] = '1f53479e2960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'temporary', 'internship', name='employment_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'unpublished', 'expired', name='job_posting_status'), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('fk_job_postings_requisition_id_requisitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_job_postings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings')),
    sa.UniqueConstraint('public_id', name='uq_job_postings_public_id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_job_postings_tenant_slug')
    )
    op.create_index('ix_job_postings_public_status', 'job_postings', ['public_id', 'status'], unique=False)
    op.create_index(op.f('ix_job_postings_requisition_id'), 'job_postings', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_job_postings_tenant_id'), 'job_postings', ['tenant_id'], unique=False)
    op.create_index('ix_job_postings_tenant_status_published_at', 'job_postings', ['tenant_id', 'status', 'published_at'], unique=False)
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', "(status != 'cancelled') OR cancelled_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', 'position >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', '"position" >= 1')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', "status <> 'completed'::onboarding_instance_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', "status <> 'cancelled'::onboarding_instance_status OR cancelled_at IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    op.drop_index('ix_job_postings_tenant_status_published_at', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_tenant_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_requisition_id'), table_name='job_postings')
    op.drop_index('ix_job_postings_public_status', table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
