"""add application pipeline history

Revision ID: 2653626d7543
Revises: c9f5dec47497
Create Date: 2026-09-07 19:16:08.139621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2653626d7543'
down_revision: Union[str, Sequence[str], None] = 'c9f5dec47497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('applied', 'screening', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='application_status'), nullable=True),
    sa.Column('to_status', sa.Enum('applied', 'screening', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='application_status'), nullable=False),
    sa.Column('rejection_reason', sa.Enum('not_qualified', 'better_matched_candidate', 'failed_assessment', 'compensation_mismatch', 'role_closed', 'other', name='application_rejection_reason'), nullable=True),
    sa.Column('transitioned_by_subject', sa.String(length=255), nullable=False),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_stage_history_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_application_stage_history_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_stage_history'))
    )
    op.create_index(op.f('ix_application_stage_history_application_id'), 'application_stage_history', ['application_id'], unique=False)
    op.create_index('ix_application_stage_history_tenant_application_transitioned_at', 'application_stage_history', ['tenant_id', 'application_id', 'transitioned_at'], unique=False)
    op.create_index(op.f('ix_application_stage_history_tenant_id'), 'application_stage_history', ['tenant_id'], unique=False)
    op.add_column('applications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('applications', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'version')
    op.drop_column('applications', 'updated_at')
    op.drop_index(op.f('ix_application_stage_history_tenant_id'), table_name='application_stage_history')
    op.drop_index('ix_application_stage_history_tenant_application_transitioned_at', table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_application_id'), table_name='application_stage_history')
    op.drop_table('application_stage_history')
    # ### end Alembic commands ###
