"""add notification preferences and intents

Revision ID: 3bc6e17df7b3
Revises: 7c3da3570b11
Create Date: 2026-09-10 09:41:00.333305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc6e17df7b3'
down_revision: Union[str, Sequence[str], None] = '7c3da3570b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('email', name='notification_channel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notification_preferences_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('tenant_id', 'user_id', 'event_type', 'channel', name='uq_notification_preferences_tenant_user_event_channel')
    )
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=False)
    op.create_index('ix_notification_preferences_tenant_user', 'notification_preferences', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('email', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sending', 'sent', 'failed', 'cancelled', name='notification_status'), server_default='pending', nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('deduplication_key', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status != 'cancelled') OR cancelled_at IS NOT NULL", name=op.f('ck_notifications_ck_notifications_cancelled_at_required')),
    sa.CheckConstraint("(status != 'failed') OR failed_at IS NOT NULL", name=op.f('ck_notifications_ck_notifications_failed_at_required')),
    sa.CheckConstraint("(status != 'sent') OR sent_at IS NOT NULL", name=op.f('ck_notifications_ck_notifications_sent_at_required')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_notifications_ck_notifications_attempts_non_negative')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('tenant_id', 'recipient_user_id', 'channel', 'event_type', 'deduplication_key', name='uq_notifications_tenant_recipient_event_deduplication')
    )
    op.create_index('ix_notifications_recipient_status', 'notifications', ['recipient_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_tenant_status_scheduled_at', 'notifications', ['tenant_id', 'status', 'scheduled_at'], unique=False)
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', "(status != 'cancelled') OR cancelled_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', 'position >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', '"position" >= 1')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', "status <> 'completed'::onboarding_instance_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', "status <> 'cancelled'::onboarding_instance_status OR cancelled_at IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    op.drop_index('ix_notifications_tenant_status_scheduled_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index('ix_notification_preferences_tenant_user', table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
