"""add application debrief decisions

Revision ID: 417075efc387
Revises: f8b6443d1c61
Create Date: 2026-09-09 12:01:16.098646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '417075efc387'
down_revision: Union[str, Sequence[str], None] = 'f8b6443d1c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    application_rejection_reason = postgresql.ENUM(
        "not_qualified",
        "better_matched_candidate",
        "failed_assessment",
        "compensation_mismatch",
        "role_closed",
        "other",
        name="application_rejection_reason",
        create_type=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_debriefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('advance_to_offer', 'reject', name='hiring_decision'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('rejection_reason', application_rejection_reason, nullable=True),
    sa.Column('decided_by_subject', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(decision != 'reject') OR rejection_reason IS NOT NULL", name=op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required')),
    sa.CheckConstraint("(decision = 'reject') OR rejection_reason IS NULL", name=op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject')),
    sa.CheckConstraint('char_length(rationale) BETWEEN 1 AND 5000', name=op.f('ck_application_debriefs_ck_application_debriefs_rationale_length')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_debriefs_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_application_debriefs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_debriefs')),
    sa.UniqueConstraint('tenant_id', 'application_id', name='uq_application_debriefs_tenant_application')
    )
    op.create_index(op.f('ix_application_debriefs_application_id'), 'application_debriefs', ['application_id'], unique=False)
    op.create_index('ix_application_debriefs_tenant_application', 'application_debriefs', ['tenant_id', 'application_id'], unique=False)
    op.create_index(op.f('ix_application_debriefs_tenant_id'), 'application_debriefs', ['tenant_id'], unique=False)
    op.create_table('application_decision_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('application_debrief_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('advance_to_offer', 'reject', name='hiring_decision'), nullable=False),
    sa.Column('rejection_reason', application_rejection_reason, nullable=True),
    sa.Column('decided_by_subject', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['application_debrief_id'], ['application_debriefs.id'], name=op.f('fk_application_decision_history_application_debrief_id_application_debriefs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_decision_history_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_application_decision_history_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_decision_history'))
    )
    op.create_index(op.f('ix_application_decision_history_application_debrief_id'), 'application_decision_history', ['application_debrief_id'], unique=False)
    op.create_index(op.f('ix_application_decision_history_application_id'), 'application_decision_history', ['application_id'], unique=False)
    op.create_index('ix_application_decision_history_tenant_application_decided_at', 'application_decision_history', ['tenant_id', 'application_id', 'decided_at'], unique=False)
    op.create_index(op.f('ix_application_decision_history_tenant_id'), 'application_decision_history', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION prevent_application_decision_history_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'Application decision history is immutable.'
                USING ERRCODE = '55000';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_application_decision_history_immutable
        BEFORE UPDATE OR DELETE ON application_decision_history
        FOR EACH ROW
        EXECUTE FUNCTION prevent_application_decision_history_mutation();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_application_decision_history_immutable "
        "ON application_decision_history"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS prevent_application_decision_history_mutation()"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_index(op.f('ix_application_decision_history_tenant_id'), table_name='application_decision_history')
    op.drop_index('ix_application_decision_history_tenant_application_decided_at', table_name='application_decision_history')
    op.drop_index(op.f('ix_application_decision_history_application_id'), table_name='application_decision_history')
    op.drop_index(op.f('ix_application_decision_history_application_debrief_id'), table_name='application_decision_history')
    op.drop_table('application_decision_history')
    op.drop_index(op.f('ix_application_debriefs_tenant_id'), table_name='application_debriefs')
    op.drop_index('ix_application_debriefs_tenant_application', table_name='application_debriefs')
    op.drop_index(op.f('ix_application_debriefs_application_id'), table_name='application_debriefs')
    op.drop_table('application_debriefs')
    # ### end Alembic commands ###
