"""add candidate and application tables

Revision ID: 4add0a0fcf9f
Revises: 9d1b1fb60257
Create Date: 2026-09-05 10:23:46.348846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4add0a0fcf9f'
down_revision: Union[str, Sequence[str], None] = '9d1b1fb60257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('consent_status', sa.Enum('unknown', 'granted', 'withdrawn', name='candidate_consent_status'), server_default='unknown', nullable=False),
    sa.Column('consent_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_candidates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('tenant_id', 'normalized_email', name='uq_candidates_tenant_normalized_email')
    )
    op.create_index('ix_candidates_tenant_created_at', 'candidates', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_candidates_tenant_id'), 'candidates', ['tenant_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'hired', 'rejected', 'withdrawn', name='application_status'), server_default='applied', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_applications_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('fk_applications_requisition_id_requisitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_applications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('tenant_id', 'candidate_id', 'requisition_id', name='uq_applications_tenant_candidate_requisition')
    )
    op.create_index('ix_applications_tenant_candidate_id', 'applications', ['tenant_id', 'candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_index('ix_applications_tenant_requisition_status_applied_at', 'applications', ['tenant_id', 'requisition_id', 'status', 'applied_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_applications_tenant_requisition_status_applied_at', table_name='applications')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index('ix_applications_tenant_candidate_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_candidates_tenant_id'), table_name='candidates')
    op.drop_index('ix_candidates_tenant_created_at', table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
