"""add offer approval tables

Revision ID: 4b4936fa6a71
Revises: c1a02abc0cdd
Create Date: 2026-09-09 13:59:52.935510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b4936fa6a71'
down_revision: Union[str, Sequence[str], None] = 'c1a02abc0cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    approval_status = postgresql.ENUM(
        "pending",
        "approved",
        "rejected",
        name="approval_status",
        create_type=False,
    )
    approval_decision_status = postgresql.ENUM(
        "pending",
        "approved",
        "rejected",
        name="approval_decision_status",
        create_type=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('approval_policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', approval_status, server_default='pending', nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('submitted_by_subject', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt >= 1', name=op.f('ck_offer_approvals_ck_offer_approvals_attempt_positive')),
    sa.CheckConstraint('current_step >= 1', name=op.f('ck_offer_approvals_ck_offer_approvals_current_step_positive')),
    sa.ForeignKeyConstraint(['approval_policy_id'], ['approval_policies.id'], name=op.f('fk_offer_approvals_approval_policy_id_approval_policies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_approvals_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_offer_approvals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_approvals')),
    sa.UniqueConstraint('offer_id', 'attempt', name='uq_offer_approvals_offer_attempt')
    )
    op.create_index(op.f('ix_offer_approvals_offer_id'), 'offer_approvals', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_approvals_tenant_id'), 'offer_approvals', ['tenant_id'], unique=False)
    op.create_index('ix_offer_approvals_tenant_status', 'offer_approvals', ['tenant_id', 'status'], unique=False)
    op.create_index('uq_offer_approvals_one_pending_per_offer', 'offer_approvals', ['offer_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('offer_approval_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_approval_id', sa.UUID(), nullable=False),
    sa.Column('step_position', sa.Integer(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('status', approval_decision_status, server_default='pending', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_offer_approval_decisions_approver_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_approval_id'], ['offer_approvals.id'], name=op.f('fk_offer_approval_decisions_offer_approval_id_offer_approvals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_approval_decisions')),
    sa.UniqueConstraint('offer_approval_id', 'step_position', name='uq_offer_approval_decisions_step')
    )
    op.create_index('ix_offer_approval_decisions_approver_status', 'offer_approval_decisions', ['approver_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_offer_approval_decisions_approver_user_id'), 'offer_approval_decisions', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_offer_approval_decisions_offer_approval_id'), 'offer_approval_decisions', ['offer_approval_id'], unique=False)
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    op.drop_index(op.f('ix_offer_approval_decisions_offer_approval_id'), table_name='offer_approval_decisions')
    op.drop_index(op.f('ix_offer_approval_decisions_approver_user_id'), table_name='offer_approval_decisions')
    op.drop_index('ix_offer_approval_decisions_approver_status', table_name='offer_approval_decisions')
    op.drop_table('offer_approval_decisions')
    op.drop_index('uq_offer_approvals_one_pending_per_offer', table_name='offer_approvals', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_offer_approvals_tenant_status', table_name='offer_approvals')
    op.drop_index(op.f('ix_offer_approvals_tenant_id'), table_name='offer_approvals')
    op.drop_index(op.f('ix_offer_approvals_offer_id'), table_name='offer_approvals')
    op.drop_table('offer_approvals')
    # ### end Alembic commands ###
