"""add calendar integration persistence

Revision ID: 5311e8b7141d
Revises: ac2a04a0b6e1
Create Date: 2026-09-12 18:07:02.901336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5311e8b7141d'
down_revision: Union[str, Sequence[str], None] = 'ac2a04a0b6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'microsoft', name='calendar_provider'), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', name='calendar_connection_status'), server_default='active', nullable=False),
    sa.Column('credential_reference', sa.String(length=500), nullable=False),
    sa.Column('external_calendar_id', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_calendar_connections_owner_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_calendar_connections_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_connections')),
    sa.UniqueConstraint('credential_reference', name=op.f('uq_calendar_connections_credential_reference')),
    sa.UniqueConstraint('tenant_id', 'owner_user_id', 'provider', name='uq_calendar_connections_tenant_owner_provider')
    )
    op.create_index(op.f('ix_calendar_connections_owner_user_id'), 'calendar_connections', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_calendar_connections_tenant_id'), 'calendar_connections', ['tenant_id'], unique=False)
    op.create_index('ix_calendar_connections_tenant_status', 'calendar_connections', ['tenant_id', 'status'], unique=False)
    op.create_table('interview_calendar_syncs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=False),
    sa.Column('calendar_connection_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'synced', 'failed', 'disabled', name='interview_calendar_sync_status'), server_default='pending', nullable=False),
    sa.Column('external_event_id', sa.String(length=500), nullable=True),
    sa.Column('external_idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('desired_interview_version', sa.Integer(), nullable=False),
    sa.Column('synced_interview_version', sa.Integer(), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_connection_id'], ['calendar_connections.id'], name=op.f('fk_interview_calendar_syncs_calendar_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], name=op.f('fk_interview_calendar_syncs_interview_session_id_interview_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_interview_calendar_syncs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_calendar_syncs')),
    sa.UniqueConstraint('calendar_connection_id', 'interview_session_id', name='uq_interview_calendar_syncs_connection_session'),
    sa.UniqueConstraint('external_idempotency_key', name='uq_interview_calendar_syncs_external_idempotency_key')
    )
    op.create_index(op.f('ix_interview_calendar_syncs_calendar_connection_id'), 'interview_calendar_syncs', ['calendar_connection_id'], unique=False)
    op.create_index('ix_interview_calendar_syncs_interview_session', 'interview_calendar_syncs', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_interview_calendar_syncs_interview_session_id'), 'interview_calendar_syncs', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_interview_calendar_syncs_tenant_id'), 'interview_calendar_syncs', ['tenant_id'], unique=False)
    op.create_index('ix_interview_calendar_syncs_tenant_status_updated_at', 'interview_calendar_syncs', ['tenant_id', 'status', 'updated_at'], unique=False)
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', "(status != 'cancelled') OR cancelled_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', 'position >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', '"position" >= 1')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', "status <> 'completed'::onboarding_instance_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', "status <> 'cancelled'::onboarding_instance_status OR cancelled_at IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    op.drop_index('ix_interview_calendar_syncs_tenant_status_updated_at', table_name='interview_calendar_syncs')
    op.drop_index(op.f('ix_interview_calendar_syncs_tenant_id'), table_name='interview_calendar_syncs')
    op.drop_index(op.f('ix_interview_calendar_syncs_interview_session_id'), table_name='interview_calendar_syncs')
    op.drop_index('ix_interview_calendar_syncs_interview_session', table_name='interview_calendar_syncs')
    op.drop_index(op.f('ix_interview_calendar_syncs_calendar_connection_id'), table_name='interview_calendar_syncs')
    op.drop_table('interview_calendar_syncs')
    op.drop_index('ix_calendar_connections_tenant_status', table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_tenant_id'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_owner_user_id'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
