"""add interview feedback table

Revision ID: 5404bc192de4
Revises: bd4dbe2acea1
Create Date: 2026-09-08 14:43:57.247504

"""
# pylint: disable=invalid-name,line-too-long
# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5404bc192de4'
down_revision: str | Sequence[str] | None = 'bd4dbe2acea1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=False),
    sa.Column('interviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', name='interview_feedback_status'), server_default='draft', nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.Enum('strong_no', 'no', 'yes', 'strong_yes', name='interview_recommendation'), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status != 'submitted') OR (overall_rating IS NOT NULL AND recommendation IS NOT NULL AND submitted_at IS NOT NULL)", name=op.f('ck_interview_feedback_ck_interview_feedback_submitted_complete')),
    sa.CheckConstraint("(status = 'submitted') OR submitted_at IS NULL", name=op.f('ck_interview_feedback_ck_interview_feedback_draft_not_submitted')),
    sa.CheckConstraint('overall_rating IS NULL OR overall_rating BETWEEN 1 AND 5', name=op.f('ck_interview_feedback_ck_interview_feedback_rating_range')),
    sa.ForeignKeyConstraint(['interview_session_id', 'interviewer_user_id'], ['interview_participants.interview_session_id', 'interview_participants.user_id'], name='fk_interview_feedback_assigned_participant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_interview_feedback_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_feedback')),
    sa.UniqueConstraint('tenant_id', 'interview_session_id', 'interviewer_user_id', name='uq_interview_feedback_tenant_session_interviewer')
    )
    op.create_index(op.f('ix_interview_feedback_interview_session_id'), 'interview_feedback', ['interview_session_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_interviewer_user_id'), 'interview_feedback', ['interviewer_user_id'], unique=False)
    op.create_index(op.f('ix_interview_feedback_tenant_id'), 'interview_feedback', ['tenant_id'], unique=False)
    op.create_index('ix_interview_feedback_tenant_interviewer_status', 'interview_feedback', ['tenant_id', 'interviewer_user_id', 'status'], unique=False)
    op.create_index('ix_interview_feedback_tenant_session', 'interview_feedback', ['tenant_id', 'interview_session_id'], unique=False)
    op.execute(
        """
        CREATE FUNCTION prevent_submitted_interview_feedback_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.status = 'submitted' THEN
                RAISE EXCEPTION 'Submitted interview feedback is immutable.'
                    USING ERRCODE = '55000';
            END IF;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;

            RETURN NEW;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_interview_feedback_immutable_after_submission
        BEFORE UPDATE OR DELETE ON interview_feedback
        FOR EACH ROW
        EXECUTE FUNCTION prevent_submitted_interview_feedback_mutation();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS "
        "trg_interview_feedback_immutable_after_submission "
        "ON interview_feedback"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS prevent_submitted_interview_feedback_mutation()"
    )
    op.drop_index('ix_interview_feedback_tenant_session', table_name='interview_feedback')
    op.drop_index('ix_interview_feedback_tenant_interviewer_status', table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_tenant_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_interviewer_user_id'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_interview_session_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    # ### end Alembic commands ###
