"""add onboarding foundation tables

Revision ID: 7c3da3570b11
Revises: 634be0d89f10
Create Date: 2026-09-09 22:33:47.974429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c3da3570b11'
down_revision: Union[str, Sequence[str], None] = '634be0d89f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role = postgresql.ENUM(
    "tenant_admin",
    "recruiter",
    "hiring_manager",
    "interviewer",
    "people_operations",
    "analyst",
    name="user_role",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_templates')),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_onboarding_templates_tenant_name_version')
    )
    op.create_index('ix_onboarding_templates_tenant_active', 'onboarding_templates', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_onboarding_templates_tenant_id'), 'onboarding_templates', ['tenant_id'], unique=False)
    op.create_table('onboarding_template_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onboarding_template_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_offset_days', sa.Integer(), nullable=True),
    sa.Column('default_assignee_role', user_role, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('due_offset_days IS NULL OR due_offset_days >= 0', name=op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative')),
    sa.CheckConstraint('position >= 1', name=op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive')),
    sa.ForeignKeyConstraint(['onboarding_template_id'], ['onboarding_templates.id'], name=op.f('fk_onboarding_template_tasks_onboarding_template_id_onboarding_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_template_tasks')),
    sa.UniqueConstraint('onboarding_template_id', 'position', name='uq_onboarding_template_tasks_template_position')
    )
    op.create_index(op.f('ix_onboarding_template_tasks_onboarding_template_id'), 'onboarding_template_tasks', ['onboarding_template_id'], unique=False)
    op.create_table('onboarding_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_template_id', sa.UUID(), nullable=False),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='onboarding_instance_status'), server_default='active', nullable=False),
    sa.Column('started_by_subject', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status != 'cancelled') OR cancelled_at IS NOT NULL", name=op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required')),
    sa.CheckConstraint("(status != 'completed') OR completed_at IS NOT NULL", name=op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_onboarding_instances_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['onboarding_template_id'], ['onboarding_templates.id'], name=op.f('fk_onboarding_instances_onboarding_template_id_onboarding_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_instances_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_instances')),
    sa.UniqueConstraint('tenant_id', 'application_id', name='uq_onboarding_instances_tenant_application')
    )
    op.create_index(op.f('ix_onboarding_instances_application_id'), 'onboarding_instances', ['application_id'], unique=False)
    op.create_index(op.f('ix_onboarding_instances_tenant_id'), 'onboarding_instances', ['tenant_id'], unique=False)
    op.create_index('ix_onboarding_instances_tenant_status_started_at', 'onboarding_instances', ['tenant_id', 'status', 'started_at'], unique=False)
    op.create_table('onboarding_instance_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_instance_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('started', 'completed', 'cancelled', name='onboarding_instance_event_type'), nullable=False),
    sa.Column('from_status', sa.Enum('active', 'completed', 'cancelled', name='onboarding_instance_status'), nullable=True),
    sa.Column('to_status', sa.Enum('active', 'completed', 'cancelled', name='onboarding_instance_status'), nullable=False),
    sa.Column('occurred_by_subject', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_instance_id'], ['onboarding_instances.id'], name=op.f('fk_onboarding_instance_history_onboarding_instance_id_onboarding_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_instance_history_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_instance_history'))
    )
    op.create_index(op.f('ix_onboarding_instance_history_onboarding_instance_id'), 'onboarding_instance_history', ['onboarding_instance_id'], unique=False)
    op.create_index(op.f('ix_onboarding_instance_history_tenant_id'), 'onboarding_instance_history', ['tenant_id'], unique=False)
    op.create_index('ix_onboarding_instance_history_tenant_instance_occurred_at', 'onboarding_instance_history', ['tenant_id', 'onboarding_instance_id', 'occurred_at'], unique=False)
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_instance_id', sa.UUID(), nullable=False),
    sa.Column('template_task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', 'blocked', 'cancelled', name='onboarding_task_status'), server_default='not_started', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status != 'completed') OR completed_at IS NOT NULL", name=op.f('ck_onboarding_tasks_ck_onboarding_tasks_completed_at_required')),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], name=op.f('fk_onboarding_tasks_assignee_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['onboarding_instance_id'], ['onboarding_instances.id'], name=op.f('fk_onboarding_tasks_onboarding_instance_id_onboarding_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_task_id'], ['onboarding_template_tasks.id'], name=op.f('fk_onboarding_tasks_template_task_id_onboarding_template_tasks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_tasks_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_tasks'))
    )
    op.create_index('ix_onboarding_tasks_assignee_status', 'onboarding_tasks', ['assignee_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_onboarding_tasks_assignee_user_id'), 'onboarding_tasks', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_onboarding_tasks_onboarding_instance_id'), 'onboarding_tasks', ['onboarding_instance_id'], unique=False)
    op.create_index(op.f('ix_onboarding_tasks_tenant_id'), 'onboarding_tasks', ['tenant_id'], unique=False)
    op.create_index('ix_onboarding_tasks_tenant_status_due_at', 'onboarding_tasks', ['tenant_id', 'status', 'due_at'], unique=False)
    op.create_table('onboarding_task_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_task_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'assigned', 'due_date_changed', 'status_changed', 'completed', 'blocked', 'cancelled', name='onboarding_task_event_type'), nullable=False),
    sa.Column('from_status', sa.Enum('not_started', 'in_progress', 'completed', 'blocked', 'cancelled', name='onboarding_task_status'), nullable=True),
    sa.Column('to_status', sa.Enum('not_started', 'in_progress', 'completed', 'blocked', 'cancelled', name='onboarding_task_status'), nullable=False),
    sa.Column('occurred_by_subject', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_task_id'], ['onboarding_tasks.id'], name=op.f('fk_onboarding_task_history_onboarding_task_id_onboarding_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_onboarding_task_history_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_task_history'))
    )
    op.create_index(op.f('ix_onboarding_task_history_onboarding_task_id'), 'onboarding_task_history', ['onboarding_task_id'], unique=False)
    op.create_index(op.f('ix_onboarding_task_history_tenant_id'), 'onboarding_task_history', ['tenant_id'], unique=False)
    op.create_index('ix_onboarding_task_history_tenant_task_occurred_at', 'onboarding_task_history', ['tenant_id', 'onboarding_task_id', 'occurred_at'], unique=False)
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION prevent_onboarding_instance_history_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'Onboarding instance history is immutable.'
                USING ERRCODE = '55000';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_onboarding_instance_history_immutable
        BEFORE UPDATE OR DELETE ON onboarding_instance_history
        FOR EACH ROW
        EXECUTE FUNCTION prevent_onboarding_instance_history_mutation();
        """
    )
    op.execute(
        """
        CREATE FUNCTION prevent_onboarding_task_history_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'Onboarding task history is immutable.'
                USING ERRCODE = '55000';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_onboarding_task_history_immutable
        BEFORE UPDATE OR DELETE ON onboarding_task_history
        FOR EACH ROW
        EXECUTE FUNCTION prevent_onboarding_task_history_mutation();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_onboarding_task_history_immutable "
        "ON onboarding_task_history"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS prevent_onboarding_task_history_mutation()"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS trg_onboarding_instance_history_immutable "
        "ON onboarding_instance_history"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS prevent_onboarding_instance_history_mutation()"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    op.drop_index('ix_onboarding_task_history_tenant_task_occurred_at', table_name='onboarding_task_history')
    op.drop_index(op.f('ix_onboarding_task_history_tenant_id'), table_name='onboarding_task_history')
    op.drop_index(op.f('ix_onboarding_task_history_onboarding_task_id'), table_name='onboarding_task_history')
    op.drop_table('onboarding_task_history')
    op.drop_index('ix_onboarding_tasks_tenant_status_due_at', table_name='onboarding_tasks')
    op.drop_index(op.f('ix_onboarding_tasks_tenant_id'), table_name='onboarding_tasks')
    op.drop_index(op.f('ix_onboarding_tasks_onboarding_instance_id'), table_name='onboarding_tasks')
    op.drop_index(op.f('ix_onboarding_tasks_assignee_user_id'), table_name='onboarding_tasks')
    op.drop_index('ix_onboarding_tasks_assignee_status', table_name='onboarding_tasks')
    op.drop_table('onboarding_tasks')
    op.drop_index('ix_onboarding_instance_history_tenant_instance_occurred_at', table_name='onboarding_instance_history')
    op.drop_index(op.f('ix_onboarding_instance_history_tenant_id'), table_name='onboarding_instance_history')
    op.drop_index(op.f('ix_onboarding_instance_history_onboarding_instance_id'), table_name='onboarding_instance_history')
    op.drop_table('onboarding_instance_history')
    op.drop_index('ix_onboarding_instances_tenant_status_started_at', table_name='onboarding_instances')
    op.drop_index(op.f('ix_onboarding_instances_tenant_id'), table_name='onboarding_instances')
    op.drop_index(op.f('ix_onboarding_instances_application_id'), table_name='onboarding_instances')
    op.drop_table('onboarding_instances')
    op.drop_index(op.f('ix_onboarding_template_tasks_onboarding_template_id'), table_name='onboarding_template_tasks')
    op.drop_table('onboarding_template_tasks')
    op.drop_index(op.f('ix_onboarding_templates_tenant_id'), table_name='onboarding_templates')
    op.drop_index('ix_onboarding_templates_tenant_active', table_name='onboarding_templates')
    op.drop_table('onboarding_templates')
    # ### end Alembic commands ###
