"""add requisition approval tables

Revision ID: 9d1b1fb60257
Revises: f105bac21333
Create Date: 2026-09-04 21:57:26.660845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d1b1fb60257'
down_revision: Union[str, Sequence[str], None] = 'f105bac21333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approval_policies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_policies')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_approval_policies_tenant_id'))
    )
    op.create_index(op.f('ix_approval_policies_tenant_id'), 'approval_policies', ['tenant_id'], unique=False)
    op.create_index('uq_approval_policies_tenant_default', 'approval_policies', ['tenant_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('approval_policy_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_policy_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approval_policy_id'], ['approval_policies.id'], name=op.f('fk_approval_policy_steps_approval_policy_id_approval_policies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_approval_policy_steps_approver_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_policy_steps')),
    sa.UniqueConstraint('approval_policy_id', 'position', name=op.f('uq_approval_policy_steps_approval_policy_id'))
    )
    op.create_index(op.f('ix_approval_policy_steps_approval_policy_id'), 'approval_policy_steps', ['approval_policy_id'], unique=False)
    op.create_index(op.f('ix_approval_policy_steps_approver_user_id'), 'approval_policy_steps', ['approver_user_id'], unique=False)
    op.create_table('requisition_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('approval_policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), server_default='pending', nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('submitted_by_subject', sa.String(length=255), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_policy_id'], ['approval_policies.id'], name=op.f('fk_requisition_approvals_approval_policy_id_approval_policies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], name=op.f('fk_requisition_approvals_requisition_id_requisitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_requisition_approvals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisition_approvals'))
    )
    op.create_index(op.f('ix_requisition_approvals_requisition_id'), 'requisition_approvals', ['requisition_id'], unique=False)
    op.create_index('ix_requisition_approvals_requisition_status', 'requisition_approvals', ['requisition_id', 'status'], unique=False)
    op.create_index(op.f('ix_requisition_approvals_tenant_id'), 'requisition_approvals', ['tenant_id'], unique=False)
    op.create_index('ix_requisition_approvals_tenant_status', 'requisition_approvals', ['tenant_id', 'status'], unique=False)
    op.create_table('requisition_approval_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requisition_approval_id', sa.UUID(), nullable=False),
    sa.Column('step_position', sa.Integer(), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_decision_status'), server_default='pending', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_requisition_approval_decisions_approver_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisition_approval_id'], ['requisition_approvals.id'], name=op.f('fk_requisition_approval_decisions_requisition_approval_id_requisition_approvals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requisition_approval_decisions')),
    sa.UniqueConstraint('requisition_approval_id', 'step_position', name=op.f('uq_requisition_approval_decisions_requisition_approval_id'))
    )
    op.create_index('ix_requisition_approval_decisions_approver_status', 'requisition_approval_decisions', ['approver_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_requisition_approval_decisions_requisition_approval_id'), 'requisition_approval_decisions', ['requisition_approval_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisition_approval_decisions_requisition_approval_id'), table_name='requisition_approval_decisions')
    op.drop_index('ix_requisition_approval_decisions_approver_status', table_name='requisition_approval_decisions')
    op.drop_table('requisition_approval_decisions')
    op.drop_index('ix_requisition_approvals_tenant_status', table_name='requisition_approvals')
    op.drop_index(op.f('ix_requisition_approvals_tenant_id'), table_name='requisition_approvals')
    op.drop_index('ix_requisition_approvals_requisition_status', table_name='requisition_approvals')
    op.drop_index(op.f('ix_requisition_approvals_requisition_id'), table_name='requisition_approvals')
    op.drop_table('requisition_approvals')
    op.drop_index(op.f('ix_approval_policy_steps_approver_user_id'), table_name='approval_policy_steps')
    op.drop_index(op.f('ix_approval_policy_steps_approval_policy_id'), table_name='approval_policy_steps')
    op.drop_table('approval_policy_steps')
    op.drop_index('uq_approval_policies_tenant_default', table_name='approval_policies', postgresql_where=sa.text('is_default'))
    op.drop_index(op.f('ix_approval_policies_tenant_id'), table_name='approval_policies')
    op.drop_table('approval_policies')
    # ### end Alembic commands ###
