"""add recruiting search indexes

Revision ID: b2937f90194b
Revises: 875a9ae0736c
Create Date: 2026-09-11 06:29:24.939083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2937f90194b'
down_revision: Union[str, Sequence[str], None] = '875a9ae0736c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.create_index('ix_applications_tenant_applied_at_id', 'applications', ['tenant_id', 'applied_at', 'id'], unique=False)
    op.create_index('ix_candidates_tenant_created_at_id', 'candidates', ['tenant_id', 'created_at', 'id'], unique=False)
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', "(status != 'cancelled') OR cancelled_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', "(status != 'completed') OR completed_at IS NOT NULL")
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', 'position >= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_position_positive'), 'onboarding_template_tasks', type_='check')
    op.drop_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tasks_due_offset_non_negative'), 'onboarding_template_tasks', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_98d9'), 'onboarding_template_tasks', '"position" >= 1')
    op.create_check_constraint(op.f('ck_onboarding_template_tasks_ck_onboarding_template_tas_17bd'), 'onboarding_template_tasks', 'due_offset_days IS NULL OR due_offset_days >= 0')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_completed_at_required'), 'onboarding_instances', type_='check')
    op.drop_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancelled_at_required'), 'onboarding_instances', type_='check')
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_complet_7a1b'), 'onboarding_instances', "status <> 'completed'::onboarding_instance_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_onboarding_instances_ck_onboarding_instances_cancell_7071'), 'onboarding_instances', "status <> 'cancelled'::onboarding_instance_status OR cancelled_at IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_index('ix_candidates_tenant_created_at_id', table_name='candidates')
    op.drop_index('ix_applications_tenant_applied_at_id', table_name='applications')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    # ### end Alembic commands ###
