"""add interview scheduling tables

Revision ID: bd4dbe2acea1
Revises: 2653626d7543
Create Date: 2026-09-08 10:44:26.914761

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd4dbe2acea1"
down_revision: str | Sequence[str] | None = "2653626d7543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "completed", "cancelled", name="interview_session_status"),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column("created_by_subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "scheduled_end_at > scheduled_start_at",
            name=op.f("ck_interview_sessions_ck_interview_sessions_positive_duration"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_interview_sessions_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_interview_sessions_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_sessions")),
    )
    op.create_index(
        op.f("ix_interview_sessions_application_id"),
        "interview_sessions",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "ix_interview_sessions_tenant_application_start",
        "interview_sessions",
        ["tenant_id", "application_id", "scheduled_start_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_sessions_tenant_id"), "interview_sessions", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_interview_sessions_tenant_status_start",
        "interview_sessions",
        ["tenant_id", "status", "scheduled_start_at"],
        unique=False,
    )
    op.create_table(
        "interview_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("interview_session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("interviewer", "coordinator", name="interview_participant_role"),
            nullable=False,
        ),
        sa.Column("scheduled_time_range", postgresql.TSTZRANGE(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("tenant_id"), "="),
            (sa.column("user_id"), "="),
            (sa.column("scheduled_time_range"), "&&"),
            using="gist",
            name="excl_interview_participants_user_time_overlap",
        ),
        sa.ForeignKeyConstraint(
            ["interview_session_id"],
            ["interview_sessions.id"],
            name=op.f("fk_interview_participants_interview_session_id_interview_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_interview_participants_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_interview_participants_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_participants")),
        sa.UniqueConstraint(
            "interview_session_id", "user_id", name="uq_interview_participants_session_user"
        ),
    )
    op.create_index(
        op.f("ix_interview_participants_interview_session_id"),
        "interview_participants",
        ["interview_session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_participants_tenant_id"),
        "interview_participants",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_interview_participants_tenant_user",
        "interview_participants",
        ["tenant_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interview_participants_user_id"),
        "interview_participants",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_participants_user_id"), table_name="interview_participants")
    op.drop_index("ix_interview_participants_tenant_user", table_name="interview_participants")
    op.drop_index(op.f("ix_interview_participants_tenant_id"), table_name="interview_participants")
    op.drop_index(
        op.f("ix_interview_participants_interview_session_id"), table_name="interview_participants"
    )
    op.drop_table("interview_participants")
    op.drop_index("ix_interview_sessions_tenant_status_start", table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_tenant_id"), table_name="interview_sessions")
    op.drop_index("ix_interview_sessions_tenant_application_start", table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_application_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    # ### end Alembic commands ###
