"""add offer and lifecycle history

Revision ID: c1a02abc0cdd
Revises: 417075efc387
Create Date: 2026-09-09 13:48:10.640269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a02abc0cdd'
down_revision: Union[str, Sequence[str], None] = '417075efc387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'sent', 'accepted', 'declined', 'expired', 'cancelled', name='offer_status'), server_default='draft', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_period', sa.Enum('monthly', 'annually', name='offer_pay_period'), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('equity_summary', sa.Text(), nullable=True),
    sa.Column('proposed_start_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approval_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status != 'accepted') OR accepted_at IS NOT NULL", name=op.f('ck_offers_ck_offers_accepted_at_required')),
    sa.CheckConstraint("(status != 'cancelled') OR cancelled_at IS NOT NULL", name=op.f('ck_offers_ck_offers_cancelled_at_required')),
    sa.CheckConstraint("(status != 'declined') OR declined_at IS NOT NULL", name=op.f('ck_offers_ck_offers_declined_at_required')),
    sa.CheckConstraint("(status != 'sent') OR sent_at IS NOT NULL", name=op.f('ck_offers_ck_offers_sent_at_required')),
    sa.CheckConstraint('base_salary > 0', name=op.f('ck_offers_ck_offers_base_salary_positive')),
    sa.CheckConstraint('bonus_amount IS NULL OR bonus_amount >= 0', name=op.f('ck_offers_ck_offers_bonus_amount_non_negative')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_offers_ck_offers_currency_length')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_offers_application_id_applications'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_offers_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers'))
    )
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=False)
    op.create_index(op.f('ix_offers_tenant_id'), 'offers', ['tenant_id'], unique=False)
    op.create_index('ix_offers_tenant_status_expiry_at', 'offers', ['tenant_id', 'status', 'expires_at'], unique=False)
    op.create_index('uq_offers_one_active_offer_per_application', 'offers', ['tenant_id', 'application_id'], unique=True, postgresql_where=sa.text("status IN ('draft', 'pending_approval', 'approved', 'sent')"))
    op.create_table('offer_lifecycle_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('created', 'submitted_for_approval', 'approved', 'sent', 'accepted', 'declined', 'expired', 'cancelled', name='offer_lifecycle_event_type'), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'pending_approval', 'approved', 'sent', 'accepted', 'declined', 'expired', 'cancelled', name='offer_status'), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'pending_approval', 'approved', 'sent', 'accepted', 'declined', 'expired', 'cancelled', name='offer_status'), nullable=False),
    sa.Column('occurred_by_subject', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_offer_lifecycle_history_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_offer_lifecycle_history_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer_lifecycle_history'))
    )
    op.create_index(op.f('ix_offer_lifecycle_history_offer_id'), 'offer_lifecycle_history', ['offer_id'], unique=False)
    op.create_index(op.f('ix_offer_lifecycle_history_tenant_id'), 'offer_lifecycle_history', ['tenant_id'], unique=False)
    op.create_index('ix_offer_lifecycle_history_tenant_offer_occurred_at', 'offer_lifecycle_history', ['tenant_id', 'offer_id', 'occurred_at'], unique=False)
    op.execute(
        """
        CREATE FUNCTION prevent_offer_lifecycle_history_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'Offer lifecycle history is immutable.'
                USING ERRCODE = '55000';
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_offer_lifecycle_history_immutable
        BEFORE UPDATE OR DELETE ON offer_lifecycle_history
        FOR EACH ROW
        EXECUTE FUNCTION prevent_offer_lifecycle_history_mutation();
        """
    )
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', 'char_length(rationale) BETWEEN 1 AND 5000')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', "(decision = 'reject') OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', "(decision != 'reject') OR rejection_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', "(event_type != 'cancelled') OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', "(status != 'cancelled') OR (cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL)")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', "(status != 'completed') OR completed_at IS NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DROP TRIGGER IF EXISTS trg_offer_lifecycle_history_immutable "
        "ON offer_lifecycle_history"
    )
    op.execute(
        "DROP FUNCTION IF EXISTS prevent_offer_lifecycle_history_mutation()"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_at_required'), 'interview_sessions', type_='check')
    op.drop_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellation_metadata_required'), 'interview_sessions', type_='check')
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_completed_a_d63b'), 'interview_sessions', "status <> 'completed'::interview_session_status OR completed_at IS NOT NULL")
    op.create_check_constraint(op.f('ck_interview_sessions_ck_interview_sessions_cancellatio_a285'), 'interview_sessions', "status <> 'cancelled'::interview_session_status OR cancelled_at IS NOT NULL AND cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lifecycle_cancellation_reason_required'), 'interview_session_lifecycle_history', type_='check')
    op.create_check_constraint(op.f('ck_interview_session_lifecycle_history_ck_interview_lif_701b'), 'interview_session_lifecycle_history', "event_type <> 'cancelled'::interview_lifecycle_event_type OR cancellation_reason IS NOT NULL")
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_required'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejection_reason_only_for_reject'), 'application_debriefs', type_='check')
    op.drop_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationale_length'), 'application_debriefs', type_='check')
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_9e79'), 'application_debriefs', "decision <> 'reject'::hiring_decision OR rejection_reason IS NOT NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rejecti_3282'), 'application_debriefs', "decision = 'reject'::hiring_decision OR rejection_reason IS NULL")
    op.create_check_constraint(op.f('ck_application_debriefs_ck_application_debriefs_rationa_c861'), 'application_debriefs', 'char_length(rationale) >= 1 AND char_length(rationale) <= 5000')
    op.drop_index('ix_offer_lifecycle_history_tenant_offer_occurred_at', table_name='offer_lifecycle_history')
    op.drop_index(op.f('ix_offer_lifecycle_history_tenant_id'), table_name='offer_lifecycle_history')
    op.drop_index(op.f('ix_offer_lifecycle_history_offer_id'), table_name='offer_lifecycle_history')
    op.drop_table('offer_lifecycle_history')
    op.drop_index('uq_offers_one_active_offer_per_application', table_name='offers', postgresql_where=sa.text("status IN ('draft', 'pending_approval', 'approved', 'sent')"))
    op.drop_index('ix_offers_tenant_status_expiry_at', table_name='offers')
    op.drop_index(op.f('ix_offers_tenant_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
