"""add candidate document scan attempts

Revision ID: c9f5dec47497
Revises: ffb789e1993c
Create Date: 2026-09-07 06:33:49.885982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f5dec47497'
down_revision: Union[str, Sequence[str], None] = 'ffb789e1993c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_document_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('candidate_document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('scanning', 'clean', 'infected', 'failed', name='candidate_document_scan_status'), server_default='scanning', nullable=False),
    sa.Column('scanner_name', sa.String(length=100), nullable=True),
    sa.Column('detected_signature', sa.String(length=500), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_document_id'], ['candidate_documents.id'], name=op.f('fk_candidate_document_scans_candidate_document_id_candidate_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_candidate_document_scans_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_document_scans'))
    )
    op.create_index(op.f('ix_candidate_document_scans_candidate_document_id'), 'candidate_document_scans', ['candidate_document_id'], unique=False)
    op.create_index('ix_candidate_document_scans_status_started_at', 'candidate_document_scans', ['status', 'started_at'], unique=False)
    op.create_index('ix_candidate_document_scans_tenant_document_started_at', 'candidate_document_scans', ['tenant_id', 'candidate_document_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_candidate_document_scans_tenant_id'), 'candidate_document_scans', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_document_scans_tenant_id'), table_name='candidate_document_scans')
    op.drop_index('ix_candidate_document_scans_tenant_document_started_at', table_name='candidate_document_scans')
    op.drop_index('ix_candidate_document_scans_status_started_at', table_name='candidate_document_scans')
    op.drop_index(op.f('ix_candidate_document_scans_candidate_document_id'), table_name='candidate_document_scans')
    op.drop_table('candidate_document_scans')
    # ### end Alembic commands ###
