"""add HRIS handoff foundation"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# Keep the revision and down_revision values generated by Alembic.
revision: str = "e598614f48e1"
down_revision: Union[str, Sequence[str], None] = "b43d53402ebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create tenant-owned HRIS connections and durable handoff state."""
    hris_provider = postgresql.ENUM(
        "bamboohr",
        "hibob",
        "workday",
        "custom",
        name="hris_provider",
        create_type=False,
    )
    hris_connection_status = postgresql.ENUM(
        "active",
        "disabled",
        name="hris_connection_status",
        create_type=False,
    )
    hris_handoff_status = postgresql.ENUM(
        "pending",
        "processing",
        "succeeded",
        "retryable_failed",
        "failed",
        name="hris_handoff_status",
        create_type=False,
    )

    bind = op.get_bind()
    hris_provider.create(bind, checkfirst=True)
    hris_connection_status.create(bind, checkfirst=True)
    hris_handoff_status.create(bind, checkfirst=True)

    op.create_table(
        "hris_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider", hris_provider, nullable=False),
        sa.Column(
            "status",
            hris_connection_status,
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "credential_reference",
            sa.String(length=500),
            nullable=False,
        ),
        sa.Column(
            "created_by_subject",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "provider",
            "name",
            name="uq_hris_connections_tenant_provider_name",
        ),
        sa.UniqueConstraint(
            "credential_reference",
            name="uq_hris_connections_credential_reference",
        ),
    )
    op.create_index(
        "ix_hris_connections_tenant_id",
        "hris_connections",
        ["tenant_id"],
    )
    op.create_index(
        "ix_hris_connections_tenant_status",
        "hris_connections",
        ["tenant_id", "status"],
    )

    op.create_table(
        "hris_handoffs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("hris_connection_id", sa.UUID(), nullable=False),
        sa.Column("onboarding_instance_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            hris_handoff_status,
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "external_idempotency_key",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "external_employee_reference",
            sa.String(length=500),
            nullable=True,
        ),
        sa.Column(
            "attempt_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "last_error_code",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "last_attempt_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "succeeded_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(status != 'succeeded') OR succeeded_at IS NOT NULL",
            name="ck_hris_handoffs_succeeded_at_required",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0",
            name="ck_hris_handoffs_attempt_count_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["hris_connection_id"],
            ["hris_connections.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["onboarding_instance_id"],
            ["onboarding_instances.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "external_idempotency_key",
            name="uq_hris_handoffs_external_idempotency_key",
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "onboarding_instance_id",
            name="uq_hris_handoffs_tenant_onboarding_instance",
        ),
    )
    op.create_index(
        "ix_hris_handoffs_tenant_id",
        "hris_handoffs",
        ["tenant_id"],
    )
    op.create_index(
        "ix_hris_handoffs_hris_connection_id",
        "hris_handoffs",
        ["hris_connection_id"],
    )
    op.create_index(
        "ix_hris_handoffs_onboarding_instance_id",
        "hris_handoffs",
        ["onboarding_instance_id"],
    )
    op.create_index(
        "ix_hris_handoffs_application_id",
        "hris_handoffs",
        ["application_id"],
    )
    op.create_index(
        "ix_hris_handoffs_tenant_status_updated_at",
        "hris_handoffs",
        ["tenant_id", "status", "updated_at"],
    )
    op.create_index(
        "ix_hris_handoffs_connection_status",
        "hris_handoffs",
        ["hris_connection_id", "status"],
    )


def downgrade() -> None:
    """Remove HRIS handoff persistence."""
    op.drop_index(
        "ix_hris_handoffs_connection_status",
        table_name="hris_handoffs",
    )
    op.drop_index(
        "ix_hris_handoffs_tenant_status_updated_at",
        table_name="hris_handoffs",
    )
    op.drop_index(
        "ix_hris_handoffs_application_id",
        table_name="hris_handoffs",
    )
    op.drop_index(
        "ix_hris_handoffs_onboarding_instance_id",
        table_name="hris_handoffs",
    )
    op.drop_index(
        "ix_hris_handoffs_hris_connection_id",
        table_name="hris_handoffs",
    )
    op.drop_index(
        "ix_hris_handoffs_tenant_id",
        table_name="hris_handoffs",
    )
    op.drop_table("hris_handoffs")

    op.drop_index(
        "ix_hris_connections_tenant_status",
        table_name="hris_connections",
    )
    op.drop_index(
        "ix_hris_connections_tenant_id",
        table_name="hris_connections",
    )
    op.drop_table("hris_connections")

    bind = op.get_bind()
    postgresql.ENUM(name="hris_handoff_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="hris_connection_status").drop(bind, checkfirst=True)
    postgresql.ENUM(name="hris_provider").drop(bind, checkfirst=True)
