"""create identity and audit tables

Revision ID: e85e267c5500
Revises: 716a022cd81a
Create Date: 2026-09-01 00:21:15.229937

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e85e267c5500"
down_revision: str | Sequence[str] | None = "716a022cd81a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
