"""add candidate document metadata

Revision ID: ff5b71a1ec8a
Revises: 4add0a0fcf9f
Create Date: 2026-09-06 03:51:26.668735

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff5b71a1ec8a"
down_revision: str | Sequence[str] | None = "4add0a0fcf9f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("declared_content_type", sa.String(length=255), nullable=False),
        sa.Column("expected_byte_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending_upload",
                "uploaded",
                "scanning",
                "available",
                "quarantined",
                "rejected",
                "deleted",
                name="candidate_document_status",
            ),
            server_default="pending_upload",
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scan_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_subject", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_documents_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_candidate_documents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_documents")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_candidate_documents_storage_key")),
    )
    op.create_index(
        op.f("ix_candidate_documents_candidate_id"),
        "candidate_documents",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        "ix_candidate_documents_tenant_candidate_created_at",
        "candidate_documents",
        ["tenant_id", "candidate_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_documents_tenant_id"), "candidate_documents", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_candidate_documents_tenant_status_updated_at",
        "candidate_documents",
        ["tenant_id", "status", "updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_candidate_documents_tenant_status_updated_at", table_name="candidate_documents"
    )
    op.drop_index(op.f("ix_candidate_documents_tenant_id"), table_name="candidate_documents")
    op.drop_index(
        "ix_candidate_documents_tenant_candidate_created_at", table_name="candidate_documents"
    )
    op.drop_index(op.f("ix_candidate_documents_candidate_id"), table_name="candidate_documents")
    op.drop_table("candidate_documents")
    # ### end Alembic commands ###
